language: java
dist: trusty

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: skip

script:
  - './gradlew clean check'

before_deploy:
  - openssl aes-256-cbc -K $encrypted_49353df1995f_key -iv $encrypted_49353df1995f_iv -in key.gpg.enc -out key.gpg -d

deploy:
  # Deploy releases
  - provider: script
    script: ./gradlew publishToSonatype closeAndReleaseRepository -x test  -PossrhUsername=${SONATYPE_USERNAME} -PossrhPassword=${SONATYPE_PASSWORD} -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=key.gpg
    skip_cleanup: true
    on:
      tags: true
  # Deploy snapshots
  - provider: script
    script: ./gradlew publishToSonatype -x test -x sign  -PossrhUsername=${SONATYPE_USERNAME} -PossrhPassword=${SONATYPE_PASSWORD} -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=key.gpg
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    - secure: GE/6EmtO3BT3vICno2d2zPEcxZaAdOsMEPMsJ+1mKZ6EFB2lDhhDr4W3jN1DSDAoisEM+PXZ/PFIQhLJ9QmrE/dRL4oHALgNX/hKF+TuL+zA0so0oO5xWP1GQV9FjhueFE9aJc2JMd0Xmhd6GOBw2QzneKfrddI8W0yD4hn4KRG9hl1mffUve2fotAOy6WPtZtvUeQ5qpQPUYoQABtTUfN6tZuIcxgztqceSglh1sESv0JbJoCRj+OhHw7inJX6DvJZz8Q+YtmcKhxttVl7fDdV9DF3XpHyj6bvX584vFTBYYwH3eZ9D2fzZ9SpIkl6u9xvUmVnf0hir6AnXLM6b2Zb1xLmPU/5PMw31kqOLToic1cBI8p73EDGR6vyIIRjJ6/oE1+wx0bv/TcFRZvmvQxDfVIPxHFcHb+7RV3LDGb2SUWGA80rWWSApUrF5qSKtO7OKgormLoNvBNNmfkVESJ9eUT4jE8wvefXmQMptJgXqfVs3pieLX2d/mOY0BqcWRkmGTy+TuR3Y4Gu1yBP6hJ7Ic+ut9X9Kk4oy2oIwZNedGgUtyNFQjGDeQ3EE/RWq4zNqZ0Br7yGnL6Ahl0nnagxyQv6ovFjZMprRsK+4m+ThsTOhuimJdd0qpzVWNyP/PQYfWETGj14vK2u2fidfrNuMMEVIVzqtvh5gRrjBR+c=
    - secure: rUr9jKnYqSKKZ032Cgq+e7I5E5n1uuyUVU5968bFTC8nbYhvDdFDbC25l9hPJgzxKWJ6fovoAqAgBJ5jF8VbZRWPG0O9Vth5khUoQ8z2JODo8RR4KLxicGzH19F5gb6fVv7gPu2sLMjPo7+jR6UxQEhVUbJYYOFfVdrFp/fvJ4SbCZPsKcEc8kazbnwwfY9MESb9ZQ3bupq6CeyXuy4oCVElptVoIY9Paw1ONA3bKIsjZdWBkiKHa5JLDC9pzxMPHETezSStChI+vfFhW6XLLqHrst3PLOBMzPWSYgcVd2ogmq+6OsHGP4N5aOEjZjXxuoQSze7b8w6wlFABNJAquy05B3waxWwWuqQ/rQbeDrLPnY1D+1ORTGooOBd0wcqHYU5RXQXFeADw80wMGCMYzsIhBCuyfG1PKG0TfXIR40gU0Y3mqtqG0ZRKjPiuWkM911EuI79pqNQ00MEA6n0R6kDZ0LGohnzqrYwnbHqjKWv7L7M0Ou5rWsNrYlKZIbTmqv5DNWBNXoDxZIDWq9tpBhd1f0/IBn3f25Rpz2vr1PQWq7FmxwSjfvd/4Cqez4zPr93pU6FoKG2uTgFTTp92mTnWaKgKysVakC7hIdRNFySVddIYFdIhizbpAi6N6hpjlc+gGYXDYcTpi+o5cN4lTx3oWaiorbj+BAHoBms/dGU=
    - secure: vgCmQuIe80HAhxjrXSucEznXWY429uGdj6ZvPwLWyqxypBGS9w+cjEZfCeFml4YBL4Db0Yetdp8rUty1xQ3ylyt53HvDItRRuJgnn/aJ4p4VLoRkUI+Ot68PCJojpM1BK38ZAprsnidm1/TtTIwpBgcZS82DxmZnhfe3khH9O4li/EAaahrwjTMx0sJKbxdSmvtTNZhjv+zVDEsQ/XhgOlj2oKO5L/o9sD1+OUgJWTsOUk0WUTja1mM9LXodrXESojy+IZjaRzr8xP1TRf4l2lbeNNuD7z5MBbaRHxtV3gJIq0ZeW1UZrWUkVMOE1FLZAbiQf2Edy2N1gwPeec3HOSpMTeGtapLtJo8z/kSXHoeGpomQbS0SLpj0REOglTL/EPbM0cpm01gZOvazbvVfKsFYj6pK8XXMhCMouCino/2C/gp41Qw68AqL8wCapRn/arqpVHRt8OmBaF9SNENu3A9c2YBrDt4fjooEZ5YPEIZNCDz7rFZZKNIbgsLOAGGMaD8YujSmSE6PEeWU+s5gVizFhPzi9Weya/qMJ7mrNagY34263Zwna5OjQMgaCF7/qoVU9Soy4nAUjfhybej5cPoMgzIX29KjI/UfcyA4FkBOuwkm4ZvvWInEquuI5Cit83T6PaOermZF/SEX8ufvkDVyRaG//EK6Q2CyS6hBjmM=
    - secure: IXNBC2eXcQ294UXLFHq2S8Zfisa8mMuyxAVxwwUSbjNjbk+CrFbKpwc2V2uOzXoq+hoYAyA5F9xrThIBQS+PkUSkw99Ud+Ihp0ofAQNfMN2HD/emrNwcPy4bbZB/OgvaomyW0W8SQAWNvdHaZVu2e4K8P2/4YeY1KGO8TA1ae/7BVlL1SVlQq+wxhibrnHhE7+CU3ZUEDGej5wBdAAlJvl4wtkPax6Rxet2FoQuewGhF4WyFIjUcDlNruBDWUZQC25rgIBxoOFWhvoCKiqY+Shk4yo4lHakXeBZX8Glq2hx1qHy1AUwc9sk6vPeTjUNQ9z0OlYOfEVlGU05nHY7Nxmjl1LUK1owjyA0orImqrCQaTYgWqvbHVaQHqROoIVYkynZUrroGWxgMh+Z2HHaFswYQVKfSRgsDVKCAfsM2XZ1z6+bd9D2UZZt+lksLQg8ngoFXQCti0HS1bO8M3kauKUcaihw4yQhQL+dwgHALIdCx6iFgzdFPVPUBXrh2ZSlNCrTLQYUaHJv6yfZ8Yi2LFvQFEOsVreKetw5seoC/+DYr1PcJf8YLGhmZywGgO0gYresHQUvWdWf+KgrKUhrLwMchSVy9J4llOsvP7Art9CqX9y+7ESKlVhj+ubNtBnWbAPZirbmvJTAE5OT3O1ZhcYYFPoBX74XROc/kihnlrq4=
